### PR TITLE
Add GAFOR sectors.

### PR DESCRIPTION
**Pull request by sbrodehl**
Hi there,

after talking to @samuel-git about how to improve flight search / filtering based on location / point of interest I added GAFOR sectors to be able to filter flights based on those.
I am not sure how the software handles such large amounts of coordinates, so if needed, we can simplify the polygon shapes and reduce the amount of points.

Let me know if it's needed!

### CODE REVIEW

**Comment by moldhouse** [comment]
Thank you for contributing. At the moment, we only filter for all takeoff airports that are in the specified sector. E.g. Taunus filter would yield multiple airfields from the Taunus. However, I agree that it would be more interesting to filter for flights intersecting the areas.

In any case, I think that it should not need more than a single-digit or low two-digit number of coordinates to describe a certain area of interest. Could you simplify the sectors?

**Comment by moldhouse** [comment]
Thanks. Can you add this as a new commit so we don't have the big file in the repos history?

**Comment by sbrodehl** [comment]
So I simplified the sectors so that they still match up to each other and removed 99.9% of the coordinates.
Now, the average coordinate count is around 50.
I did not translate the names into the different languages.

Let me know if this works out!

**Comment by sbrodehl** [comment]
Another question: Should we remove the 'old' Taunus and Rheinebene sectors?
Taunus matches with the GAFOR Taunus quite good and Rheinebene can be replaced by selecting GAFOR sectors Mittlerer Oberrheingraben, Rhein-Main-Gebiet und Wetterau and Rheinpfalz und Saarland.

**Comment by moldhouse** [comment]
I think we can remove the previous sectors. Note that we'll also change the way sectors are implemented internally so that it checks for crossing (not takeoff). We will also need to think about logic when applying multiple filters (OR / AND). This will take a bit of time, but this PR is a great start.

**Comment by moldhouse** [comment]
I think it would also be sensible to limit the number of decimal places to an accuracy of not more than 10m (4/5 decimal places)

**Comment by sbrodehl** [comment]
I removed the previous sectors and reduced the precision down to at most five decimals.

Checking for crossed sectors can be tricky, off the top of my head I think simplifying flight paths (using e.g. Ramer-Douglas-Peucker) and then either using a KD-Tree to check if the path is in a sector, or checking if the flight path crosses the boundary should be feasible.

Let me know it there is anything else I can help with.

**Pull request merged**
